version: '3.8'

services:
  postgres-miner:
    container_name: postgres-miner
    image: postgres:16.3-alpine3.20
    ports:
      - "5410:5432"
    volumes:
      - "postgres-data-miner:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-miner}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeit456$}
    restart: unless-stopped

  postgres-backup:
    image: postgres:16.3-alpine3.20
    container_name: postgres-backup
    depends_on:
      - postgres-miner
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-miner}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeit456$}
    volumes:
      - ./backup:/backup # Mounting backup directory on host
    entrypoint: [ "sh", "-c", "PGPASSWORD=$${POSTGRES_PASSWORD} pg_dump --dbname=postgresql://$${POSTGRES_USER}@postgres-miner:5432/$${POSTGRES_DB} > /backup/backup_$$(date +\"%Y-%m-%d_%H-%M-%S\").sql" ]

volumes:
  postgres-data-miner:
